### ISSUE TITLE
Suggestion: Music cropping using sponsorblock

### ISSUE THREAD

**Issue by Rotekoppen** [Ryhon0/xp#1]
[Sponsorblock](https://sponsor.ajay.app/) is a user submitter database of timestamps of content in youtube videos

More spesifically it contains tinestamps for non music in music videos

I guess you get what i mean

**Comment by Ryhon0** [comment]
Should be pretty easy to add with `yt-dlp` using the `--sponsorblock-remove=music_offtopic` option. If `yt-dlp` is found, it will use it with that option, otherwise it will use `youtube-dl` without sponsorblock

**Comment by Ryhon0** [comment]
[yt-dlp#3846](https://github.com/yt-dlp/yt-dlp/issues/3846) is blocking this.
xp recodes songs because SDL2_mixer cannot load .m4a files, which are produced by youtube-dl

**Comment by Ryhon0** [comment]
Seems to be working now
